### PR TITLE
Retry fix

### LINKED ISSUE #24: pasync.retry does not implement defaults
see https://github.com/caolan/async#retry

### PR DESCRIPTION
**Pull request by crowelch**
Add support for default retry of 5 when called with just a function. Fixes #24 

Will update retry with opt param when it is in an npm release.

### CODE REVIEW

**Comment by crowelch** [comment]
+1

File: lib/index.js [hunk 1]
```diff
@@ -420,6 +420,15 @@ exports.auto = function(tasks) {
 };
 
 exports.retry = function(times, task) {
+	// Respect defaults by checking if no times is passed, or if it is passed as an object
+	if(typeof times === 'function') {
+		console.log('times is a function: ' + times);
```
Comment (crispy1989) [inline lib/index.js]: Debug code?

File: lib/index.js [hunk 2]
```diff
@@ -420,6 +420,15 @@ exports.auto = function(tasks) {
...
+		task = times;
+		times = 5;
+	} else if(typeof times === 'object') {
+		console.log('times is an object: ' + times);
```
Comment (crispy1989) [inline lib/index.js]: Debug code?
